### ISSUE TITLE
Allow setting the preferred Chrome executable

### ISSUE THREAD

**Issue by maxer456** [Srinivasa314/alcro#11]
Being able to manually select which Chrome/Chromium/Edge executable gets started would help more easily solve issues like https://github.com/JackD83/ALVR/issues/305. An app would then be able to let the user select the browser they want to use. It would also allow app developers to avoid known issues with certain browsers.

**Comment by Srinivasa314** [comment]
Do you still want this feature now that I merged `https://github.com/Srinivasa314/alcro/pull/12`

**Comment by Srinivasa314** [comment]
I made it like it will use ALCRO_BROWSER_PATH environment variable.
A rust program can also set an environment variable using `std::env::set_var`
