### ISSUE TITLE
Allow apps to have a persistend user data directory

### ISSUE THREAD

**Issue by maxer456** [Srinivasa314/alcro#13]
Having the option to keep a persistent user data directory per-app (and perhaps per-browser as well) would let apps keep their navigation data, cache, etc.

**Comment by Srinivasa314** [comment]
Refer [this](https://docs.rs/alcro/0.2.3/alcro/struct.UIBuilder.html#method.user_data_dir)

**Comment by maxer456** [comment]
I somehow missed that, sorry.
