### ISSUE TITLE
Async callbacks / ui handle

### ISSUE THREAD

**Issue by simonbuchan** [Srinivasa314/alcro#16]
So this one might be a bit confusing. Clearly you shouldn't require the user to be using e.g. `tokio` (though you could feature cfg an `bind_tokio()` wrapping this, I guess), but you could nicely support async callbacks (and some other cases) by passing a UI handle, something like this:

```rust
ui.bind_async("loadUsers", |ui: UIHandle, args: Vec<JSObject>| {
  // as an example
  tokio::spawn(async move {
    // requires ui and args are Send + 'static
    let count = 0;
    while let Some(users) = server.get_users().await {
      count += users.len();
      ui.eval("users.push(...{})", serde_json::to_string(users));
    }
    ui.resolve(json!{(count)); // or ui.set_result(Ok(json!(count)))
    // setting the result is by value, so you know when to resolve the result.
    // UIHandle::drop() will call ui.resolve(json!(null)) if it was not otherwise set
  });
});
```

At the moment this behavior is quite tricky to implement for a user, but it looks like it would only need wrapping a clone of `UI::chrome` for `alcro` itself to implement.

There's a few other ways you could structure this, of course, but I just wanted to sketch the basic idea: have a sendable handle to the UI, and set the result in a method, knowing the method has finished when the handle is closed. These don't have to be the same handle of course:

```rust
let handle = ui.handle();
ui.bind_async("loadUsers", |args, result| {
  tokio::spawn(async move {
    // ...
    handle.eval(...);
    drop(result);
  });
});
```

This is a little more flexible, as you can just hand off handles to other parts of the code, not just in UI callbacks, without having to handle the UI proper not closing any more.

Any thoughts?

**Comment by Srinivasa314** [comment]
As mentioned [here](https://docs.rs/alcro/0.5.3/alcro/struct.UI.html#method.bind), for each function call alcro spawns a separate thread. So the examples you showed wouldn't work as there would be no tokio runtime present in the thread spawned by alcro. Instead you could use a blocking executor to run async code (or pass the tokio runtime to the callback but it would be pointless as the advantage of async is that the async runtime manages a few OS threads).
Another alternative would be to rewrite alcro in async rust.

Regarding UI handles, you could access the UI from within a UI callback and use weak pointers to prevent reference cycles 
[like this](https://github.com/Srinivasa314/alcro/blob/master/examples/window-details.rs)

**Comment by simonbuchan** [comment]
Thanks for the info. I'm a bit confused about how passing the runtime would be pointless, though: even using blocking spawn you would need a runtime? I think you're saying that using async at all would be pointless as you have already pulled a separate thread from the pool, so the main benefit is lost. I think that should be fine in the example above (if it were given the runtime to make it work) as even if you're still giving a thread from the pool to the callback, it would be immediately returned for the next callback, so overall there's only the main thread (possibly also doing async stuff), the request thread pool that should only have one thread as they are returned immediately, and whatever internal scheduling the runtime is doing. If you want to allow optimizing away the thread pool, `bind_async` could simply require that the callback returns as quickly as possible (making the wrapping helper `bind_tokio` a bit more attractive as it's safer).

I'll have to try the weak handle,I don't know why I never think of them.

**Comment by Srinivasa314** [comment]
> even using blocking spawn you would need a runtime? 

Yes,my bad


As of now if you try to do a non blocking spawn there is no way to return the result of the function

> I think you're saying that using async at all would be pointless as you have already pulled a separate thread from the pool, so the main benefit is lost. I think that should be fine in the example above (if it were given the runtime to make it work) as even if you're still giving a thread from the pool to the callback, it would be immediately returned for the next callback, so overall there's only the main thread (possibly also doing async stuff), the request thread pool that should only have one thread as they are returned immediately, and whatever internal scheduling the runtime is doing. If you want to allow optimizing away the thread pool, bind_async could simply require that the callback returns as quickly as possible (making the wrapping helper bind_tokio a bit more attractive as it's safer).

It would be easy to use async if a method (like bind_async) exists that allows returning data from a function by passing a handle to the closure that allows returning data
However instead of switching to another thread then calling `runtime.spawn` each time a function is called I feel that it would be better if there is an async version of this crate(using crate features)
Feel free to submit a pull request that uses the first or second approach. The handle passed to the closure in the first approach must contain the neccessary information for it to return data.

**Comment by simonbuchan** [comment]
Sorry for the delay! I've been poking away at this after work and it seems to be mostly here in #17. Mostly not too tricky, but I'm currently not sure what's going on with user code deadlocking message processing.

At the moment `test_bind_tokio` is an example of not particularly offensive code that will deadlock. The threads are blocked on `recv_msg` in `readloop`, which look innocuous enough, and crossbeam `recv()` in `devtools::send()` in `eval()` in the test assertion. That seems like some reply is getting lost?

**Comment by Srinivasa314** [comment]
The reason for the deadlock is that `ui.eval` is a blocking function so it blocks the thread so tokio cannot spawn a task. To fix it you can use tokio::spawn_blocking(f).await to spawn it in a non blocking manner using tokio.

**Comment by Srinivasa314** [comment]
I think it wouldnt be easy for users to use tokio with this crate as alcro functions are blocking.

**Comment by simonbuchan** [comment]
Looks it works fine if `tokio/rt-multi-threaded` is enabled, no wonder I was confused. I keep getting bit by tokio using the current thread scheduler silently.

With that I think the PR is usable, even if a full async implementation might be better?

If you like, I could take a stab at that, but it seems like it would be quite a bit of impact, surely a major version upgrade.

**Comment by simonbuchan** [comment]
BTW while messing with tests I'm seeing `test_content` hanging sometimes, and needing me to kill the test process and chrome, even when the tokio tests are not enabled. Could I have broken something there?

**Comment by Srinivasa314** [comment]
> BTW while messing with tests I'm seeing `test_content` hanging sometimes, and needing me to kill the test process and chrome, even when the tokio tests are not enabled. Could I have broken something there?

I do not have that issue when I run `test_content` on your pull request. This is strange. Can you tell me what operating system you use. And could you figure out why it is hanging using a debugger?

**Comment by simonbuchan** [comment]
I'm on Windows 10. I don't think I can reproduce it now annoyingly. Might have just had Chrome in a weird state?
