### ISSUE TITLE
[QUESTION] How to tab...

### ISSUE THREAD

**Issue by ChugunovRoman** [Srinivasa314/alcro#18]
How to create tab programmatically or create multiple BrowserView's (like in Electron.js) on single window?

**Comment by Srinivasa314** [comment]
This library does not support creating multiple tabs in a single window. However you can use `<iframe>`s

**Comment by ChugunovRoman** [comment]
@Srinivasa314  thx for reply. No, iframe doesn't suit me, because I need preload and execute js code in a page before all js execution.\
For tab, need implement the `Page.ClientNavigationDisposition` method?

**Comment by Srinivasa314** [comment]
Since the browser is launched in "app mode" I dont think tabs will work.

**Comment by Srinivasa314** [comment]
https://github.com/Srinivasa314/alcro/blob/40a49b7d7f291a960c1cdc406ab55fecded00bde/src/lib.rs#L135
