### ISSUE TITLE
Local privilege escalation vulnerabilities

### ISSUE THREAD

**Issue by Demi-Marie** [Srinivasa314/alcro#2]
The code needs to be audited to ensure that an attacker who can connect to sockets running on localhost cannot compromise the system.  This can be done by ensuring that all connections over the websocket are properly encrypted and authenticated, or by switching to AF_UNIX sockets (which are protected by filesystem permissions).

**Comment by Srinivasa314** [comment]
An encrypted websocket connection cannot be established to chrome using devtools protocol. Instead I plan to use pipes . Also it will be faster.Thanks for mentioning the issue.
Since it requires significant changes to the code, I plan of doing it in the next version.

**Comment by Demi-Marie** [comment]
Pipes are good enough for this, thanks!

**Comment by Srinivasa314** [comment]
I made alcro use pipes in the pipe branch. ~~As of now this is experimental as headless chrome does not work.~~
EDIT: Now merged to master
