### ISSUE TITLE
Process not ending after UI close on MacOsX

### ISSUE THREAD

**Issue by siriux** [Srinivasa314/alcro#3]
I've tried it on windows and macosx and the example seems to work on both, but on macosx the process is not ending after the window is closed.

**Comment by Srinivasa314** [comment]
Check branch issue3 and see if it is fixed

**Comment by Srinivasa314** [comment]
Merged it to master. Check if the issue is resolved now.

**Comment by Srinivasa314** [comment]
Reopen the issue if it still exists
