### ISSUE TITLE
Can I load multiple contents

### ISSUE THREAD

**Issue by hyousefGopher** [Srinivasa314/alcro#4]
Hi.
Is there a way/possibility of load multiple contents, something like:
```rust
.content(Content::Html(include_str!("html_toolbar.html")))
.content(Content::Html(include_str!("html_content.html")))
```

**Comment by Srinivasa314** [comment]
If you want to load a different html later you can use UI::load. If you want to use many html files then you can serve them with actix. There is an example in this repo in the examples directory . In the example the files are embedded in the binary but you need not do that.
