### ISSUE TITLE
Can I access the UI from different scopes

### ISSUE THREAD

**Issue by hyousefGopher** [Srinivasa314/alcro#5]
Let's say I'm building the `ui` from the `main` scope, and in another function/scope I' generating an image using `OpenCV` and I want to push this image to `<img..>` element in the `ui` can I do it?

I was able to do the below before seeing your crate:
```rust
// opencv = {version = "0.36", features = ["buildtime-bindgen"]}
fn read_image() {
    let mut cam = videoio::VideoCapture::new_default(0)?;
    let mut frame = core::Mat::default()?;
    cam.read(&mut frame)?;
    let mut encodedImage = VectorOfu8::new();
    let mut params = VectorOfi32::new();
    match opencv::imgcodecs::imencode(".JPG", &frame,
                                              &mut encodedImage, &params).unwrap()  {
          true => { let filename = "savedImageX.jpg"; 
                          imwrite(&filename, &frame,  &params);
          },
          false => println!("not encoded")
    }
}
```
Andin the html file:
```html5
<img id="theImage" src = "http://localhost:8000/static/savedImageX.jpg">
<script>
    newImage = document.getElementById("theImage");
    (function(){
          newImage.src = "http://localhost:8000/static/savedImageX.jpg?" + new Date().getTime();
          setTimeout(arguments.callee, 1000);
    })();
</script>
```
But in many cases, JS start loading the image before it getting completely written, so part only is loaded, I need to push the image to the browser directly  after `imwrite(&filename, &frame,  &params);`

**Comment by siriux** [comment]
You can use ui.eval when you finish the image creation to change image src from the js side.

**Comment by Srinivasa314** [comment]
You can do as @siriux said or you can expose the function to javascript using UI::bind and use async/await to display the image after the function finished executing.

You can even return the bytes of the image as a base64 string from the function if you want.
