### ISSUE TITLE
Listening of browser closing

### ISSUE THREAD

**Issue by hyousefGopher** [Srinivasa314/alcro#6]
Is there a way to understand if the user closed the browser/ui? So that an alert dialoge be displayed to confirm his need to chose it?

Also is there a way to close the browser/ui from rust?

**Comment by Srinivasa314** [comment]
> Is there a way to understand if the user closed the browser/ui?

From rust you can find out whether the user closed using UI::done

> So that an alert dialoge be displayed to confirm his need to chose it?
```
window.onbeforeunload = function () {
    return "Do you really want to close?";
};
```
Two important points:
* Browsers usually ignore the return value of the function.Chrome displays "Leave app? Changes that you made may not be saved."
* This will only fire if the user did some interaction with the webpage

> Also is there a way to close the browser/ui from rust?

Yes, use UI::close

**Comment by hyousefGopher** [comment]
Trying to use it with `rocket`, where I need both `ui` and `server` to be closed upon the press of `exit` button, but stuck with `move` restrictions, any thought?

```rust
#![feature(decl_macro, proc_macro_hygiene)]

mod routes;

use rocket_contrib::serve::StaticFiles;
use rocket_contrib::templates::Template;
use std::sync::Arc;
use alcro::{UI, UIBuilder, Content, JSObject};
use std::thread::spawn;
use std::process::exit;

struct Chrome(Arc<UI>);
fn main() {
    println!("Hello, world!");

    let ui = Arc::new(
        UIBuilder::new()
            .content(Content::Url("http://localhost:8000"))
            .size(1200, 800)
            .run()
    );
    
    ui.bind("exit", move |_| {  // ui value moved into closure
        println!("good bye");
        ui.close();   // ui variable moved due to use in closure
        exit(0);
        Ok(JSObject::Null)
    });

    rocket::ignite()
        .attach(Template::fairing())
        .mount("/static",
               StaticFiles::from(concat!(env!("CARGO_MANIFEST_DIR", "/static"))))
        .mount("/", rocket::routes![routes::root::root])
        .manage(Chrome(ui))   // ui value used here after move
        .launch();
}
```bash
error[E0382]: borrow of moved value: `ui`
  --> src\main.rs:35:24
   |
16 |     let ui = Arc::new(
   |         -- move occurs because `ui` has type `std::sync::Arc<alcro::UI>`, which does not implement the `Copy` trait
...
23 |     ui.bind("exit", move |_| {  // ui value moved into closure
   |                     -------- value moved into closure here
24 |         println!("good bye");
25 |         ui.close();   // ui variable moved due to use in closure
   |         -- variable moved due to use in closure
...
35 |         .manage(Chrome(ui.clone()))   // ui value used here after move
   |                        ^^ value borrowed here after move
```

**Comment by Srinivasa314** [comment]
You should create a clone of ui (Arc::clone(&ui)) as a new variable and move it into the closure. It seems that you are a rust beginner so you can get help in users.rust-lang.org or stackoverflow instead of creating a issue.

**Comment by hyousefGopher** [comment]
Thanks, yes new to rust.
I did it as:
```rust
    let ui_clone = Arc::clone(&ui);
    ui.bind("exit", move |args| {
    match args[0].as_i64() {
            Some(0i64) => { println!("good bye: normal exit");
                ui_clone.close(); exit(0);  },
            Some(1i64) => { println!("good bye: user closed browser");
                exit(0); },
            _ => {}
    };
```
With below code JavaScript:
```javascript
<script>
     window.addEventListener('beforeunload', function (e) {
           e.preventDefault();
           e.returnValue = '';
           exit(1);
     });
</script>
<button onclick="exit(0)">Exit the app</button>
```

And it handles the application exit from within the app, or by closing the browser, the missing one is closing the `ui` before initial load completion, will search it in stackoverflow, it is JS issue.

**Comment by hyousefGopher** [comment]
It looks `closing the ui before initial load completion` can not be done through JavaScript a mentioned [here](https://stackoverflow.com/a/3888938/2441637) can we detect it from rust? 
I wrote this additional to the above:
```rust
    let ui_clone2 = Arc::clone(&ui);
    spawn(move||{
        loop {
            if ui_clone2.done() { println!("good bye: exit before load");
                exit(0); }
        }
    });
```
Do you think this is the correct way to handle it?

**Comment by Srinivasa314** [comment]
You can do this:
* Make the exit function just do ui.close()
* Do not make onbeforeunload close the ui as the user may want to cancel the close

Make the code like this:
* Launch rocket in another thread
* Launch the ui in the main thread
* Do  ui.wait_finish() in the main thread

No matter how the browser is closed wait_finish() will return
